require "erb"
require "loofah"

module P2u
  module Render
    # Renders a single P2U slide (layout + typed blocks) to HTML. Shared by the
    # static exporter and available to any render target. Markdown is sanitized;
    # diagram/equation SVGs are generated by us and inlined directly.
    class Slide
      def initialize(slide, dark: false, client_markdown: false, format: "markdown")
        @slide = slide.is_a?(Hash) ? P2u.deep_stringify(slide) : slide
        @dark = dark
        @client_markdown = client_markdown
        @format = format.to_s
      end

      attr_reader :slide

      def layout = slide["layout"].to_s.presence || "content"
      def title = slide["title"].to_s
      def body = slide["body"].to_s
      def blocks = Array(slide["blocks"])

      def to_html
        return typst_layout if @format == "typst"

        inner = case layout
        when "title", "section" then title_layout
        when "two-column" then columns("two-column", slot("left"), slot("right"))
        when "compare" then columns("compare", slot("left"), slot("right"))
        when "code-split" then columns("code-split", slot("code"), slot("prose"))
        when "full-code", "diagram", "equation" then block_html(blocks.first)
        when "metric-row" then metric_row
        when "image", "image-grid" then images
        when "quote" then quote_layout
        when "table" then block_html(blocks.first)
        else content_layout
        end

        %(<div class="p2u-slide__inner p2u-slide__inner--#{layout}">#{inner}</div>)
      end

      private
        # A Typst-format deck authors every slide body in Typst. The source is
        # compiled to a single 16:9 SVG and embedded; there is no Markdown step.
        def typst_layout
          %(<div class="p2u-slide__inner p2u-slide__inner--typst"><div class="p2u-typst">#{TypstDocument.slide(typst_source).to_svg}</div></div>)
        rescue StandardError => e
          %(<div class="p2u-slide__inner p2u-slide__inner--typst"><pre class="p2u-error" title="#{h(e.message)}">#{h(typst_source)}</pre></div>)
        end

        def typst_source
          body.presence || slide["typst"].to_s
        end

        def title_layout
          subtitle = slide["subtitle"].presence || body.presence
          parts = [ %(<h1 class="p2u-title">#{h(title)}</h1>) ]
          parts << %(<p class="p2u-subtitle">#{h(subtitle)}</p>) if subtitle.present?
          parts.join
        end

        def content_layout
          parts = []
          parts << heading if show_heading?
          parts << markdown_html(body) if body.present?
          parts.concat(blocks.map { |block| block_html(block) })
          parts.join
        end

        def show_heading?
          title.present? && title != "Untitled"
        end

        def heading
          %(<h2 class="p2u-heading">#{h(title)}</h2>)
        end

        def columns(kind, left, right)
          parts = []
          parts << heading if show_heading?
          parts << %(<div class="p2u-columns p2u-columns--#{kind}"><div class="p2u-column">#{left}</div><div class="p2u-column">#{right}</div></div>)
          parts.join
        end

        def metric_row
          cards = blocks.select { |block| block["kind"].to_s == "metric" }.map do |block|
            %(<div class="p2u-metric"><span class="p2u-metric__value">#{h(block['value'])}</span><span class="p2u-metric__label">#{h(block['label'])}</span></div>)
          end
          parts = []
          parts << heading if show_heading?
          parts << %(<div class="p2u-metrics">#{cards.join}</div>)
          parts.join
        end

        def images
          selected = blocks.select { |block| block["kind"].to_s == "image" }
          grid = selected.map { |block| image_html(block) }.join
          parts = []
          parts << heading if show_heading?
          parts << %(<div class="p2u-images p2u-images--#{layout}">#{grid}</div>)
          parts.join
        end

        def quote_layout
          block = blocks.find { |candidate| candidate["kind"].to_s == "quote" }
          return content_layout unless block

          attribution = block["attribution"].presence
          %(<blockquote class="p2u-quote"><p>#{h(block['text'])}</p>#{attribution ? %(<cite>— #{h(attribution)}</cite>) : ''}</blockquote>)
        end

        def slot(name)
          value = slide[name]
          case value
          when Hash
            value["kind"].present? ? block_html(value) : markdown_html(value["body"])
          when String then markdown_html(value)
          else ""
          end
        end

        def block_html(block)
          return "" unless block.is_a?(Hash)

          case block["kind"].to_s
          when "markdown" then markdown_html(block["body"])
          when "code" then markdown_html(fenced(block["lang"].presence || "text", block["source"]))
          when "diagram" then diagram_html(block)
          when "equation" then equation_html(block)
          when "image" then image_html(block)
          when "quote" then quote_block(block)
          when "callout" then %(<div class="p2u-callout p2u-callout--#{h(block['tone'].presence || 'note')}">#{markdown_html(block['body'])}</div>)
          when "metric" then metric_card(block)
          when "definition" then %(<dl class="p2u-definition"><dt>#{h(block['term'])}</dt><dd>#{markdown_html(block['body'])}</dd></dl>)
          when "references" then markdown_html(Array(block["items"]).map { |item| "- #{item}" }.join("\n"))
          when "table" then table_html(block)
          when "video" then %(<div class="p2u-video"><a href="#{h(block['url'])}">#{h(block['title'].presence || 'Video')}</a></div>)
          when "spacer" then %(<hr class="p2u-spacer">)
          when "notes-only" then ""
          else markdown_html(block["body"])
          end
        end

        def metric_card(block)
          %(<div class="p2u-metric"><span class="p2u-metric__value">#{h(block['value'])}</span><span class="p2u-metric__label">#{h(block['label'])}</span></div>)
        end

        def quote_block(block)
          attribution = block["attribution"].presence
          %(<blockquote class="p2u-quote"><p>#{h(block['text'])}</p>#{attribution ? %(<cite>— #{h(attribution)}</cite>) : ''}</blockquote>)
        end

        def image_html(block)
          url = block["url"].presence || block["src"].presence || block["image_url"].presence
          return "" if url.blank?

          caption = block["caption"].presence || block["alt"].presence
          figure = %(<img src="#{h(url)}" alt="#{h(block['alt'].presence || caption)}" loading="lazy">)
          figure = %(<figure>#{figure}<figcaption>#{h(caption)}</figcaption></figure>) if caption.present?
          figure
        end

        def table_html(block)
          return markdown_html(block["markdown"]) if block["markdown"].present?
          return "" unless block["columns"].is_a?(Array)

          head = block["columns"].map { |column| "<th>#{h(column)}</th>" }.join
          rows = Array(block["rows"]).map do |row|
            "<tr>#{Array(row).map { |cell| "<td>#{h(cell)}</td>" }.join}</tr>"
          end.join
          %(<table class="p2u-table"><thead><tr>#{head}</tr></thead><tbody>#{rows}</tbody></table>)
        end

        def diagram_html(block)
          source = block["source"].to_s
          return "" if source.strip.empty?

          engine = (block["lang"].presence || block["engine"].presence || "d2").to_s
          sketch = engine == "d2-sketch" || ActiveModel::Type::Boolean.new.cast(slide["sketch"])
          svg = case engine
          when "d2", "d2-sketch", "tala"
            D2Diagram.new(source, layout: "tala", sketch: sketch, theme: (@dark ? 200 : 301)).to_svg
          when "typst", "typ"
            TypstDocument.new(source).to_svg
          else
            nil
          end

          if svg
            classes = "p2u-diagram"
            classes += " p2u-diagram--sketch" if sketch
            classes += " p2u-diagram--typst" if %w[typst typ].include?(engine)
            %(<div class="#{classes}">#{svg}</div>)
          else
            markdown_html(fenced(engine, source))
          end
        rescue StandardError => e
          %(<pre class="p2u-error" title="#{h(e.message)}">#{h(source)}</pre>)
        end

        def equation_html(block)
          source = block["source"].to_s
          return "" if source.strip.empty?

          %(<div class="p2u-equation">#{LatexEquation.new(source).to_svg}</div>)
        rescue StandardError => e
          %(<pre class="p2u-error" title="#{h(e.message)}">#{h(source)}</pre>)
        end

        def markdown_html(text)
          return "" if text.blank?
          return client_markdown_html(text) if @client_markdown

          html = MarkdownRenderer.build.render(text.to_s)
          Loofah.fragment(html).scrub!(HtmlScrubber.new).to_s
        end

        # Emit Markdown for the browser to render with markdown-it, but keep the
        # server-rendered D2 / LaTeX / Typst fences: replace each with a token
        # and hand the rendered HTML to the client as a token -> HTML map.
        def client_markdown_html(text)
          assets = {}
          counter = 0

          source = text.to_s.gsub(/^```([a-zA-Z0-9_+-]*)[ \t]*\r?\n(.*?)^```[ \t]*\r?$/m) do
            language = Regexp.last_match(1).to_s.downcase
            body = Regexp.last_match(2)
            if (html = fence_html(language, body))
              token = "@@P2U_ASSET_#{counter}@@"
              assets[token] = html
              counter += 1
              "\n\n#{token}\n\n"
            else
              Regexp.last_match(0)
            end
          end

          payload = h(assets.to_json)
          %(<div class="p2u-md" data-assets="#{payload}">#{h(source)}</div>)
        end

        def fence_html(language, source)
          case language
          when "d2", "d2-sketch", "tala", "typst", "typ"
            diagram_html({ "lang" => language, "source" => source })
          when "latex", "tex", "math", "equation"
            equation_html({ "source" => source })
          end
        end

        def fenced(language, source)
          "```#{language}\n#{source}\n```"
        end

        def h(value) = ERB::Util.html_escape(value.to_s)
    end
  end
end
